### PR TITLE
framehop: remove the allocation in signal handle of framehop

### LINKED ISSUE #281: allocation in perf `perf_signal_handler`
```
 thread #1, name = 'pg', stop reason = breakpoint 4.46
  * frame #0: 0x00007f107f90ab10 libc.so.6`__libc_malloc
    frame #1: 0x000055a3eb617892 pg`std::sys::fs::unix::readlink [inlined] alloc::alloc::alloc at alloc.rs:94:9
    frame #2: 0x000055a3eb617882 pg`std::sys::fs::unix::readlink [inlined] alloc::alloc::Global::alloc_impl at alloc.rs:189:73
    frame #3: 0x000055a3eb617882 pg`std::sys::fs::unix::readlink [inlined] <alloc::alloc::Global as core::alloc::Allocator>::allocate at alloc.rs:250:14
    frame #4: 0x000055a3eb617882 pg`std::sys::fs::unix::readlink [inlined] alloc::raw_vec::RawVecInner<A>::try_allocate_in at mod.rs:476:47
    frame #5: 0x000055a3eb617877 pg`std::sys::fs::unix::readlink [inlined] alloc::raw_vec::RawVecInner<A>::with_capacity_in at mod.rs:422:15
    frame #6: 0x000055a3eb617877 pg`std::sys::fs::unix::readlink [inlined] alloc::raw_vec::RawVec<T,A>::with_capacity_in at mod.rs:190:20
    frame #7: 0x000055a3eb617877 pg`std::sys::fs::unix::readlink [inlined] alloc::vec::Vec<T,A>::with_capacity_in at mod.rs:929:20
    frame #8: 0x000055a3eb617877 pg`std::sys::fs::unix::readlink [inlined] alloc::vec::Vec<T>::with_capacity at mod.rs:500:9
    frame #9: 0x000055a3eb617877 pg`std::sys::fs::unix::readlink at unix.rs:1869:19
    frame #10: 0x000055a3eb60d557 pg`std::env::current_exe [inlined] core::ops::function::Fn::call at function.rs:80:5
    frame #11: 0x000055a3eb60d552 pg`std::env::current_exe [inlined] std::sys::pal::common::small_c_string::run_with_cstr_stack at small_c_string.rs:48:18
    frame #12: 0x000055a3eb60d54a pg`std::env::current_exe [inlined] std::sys::pal::common::small_c_string::run_with_cstr at small_c_string.rs:28:18
    frame #13: 0x000055a3eb60d54a pg`std::env::current_exe [inlined] std::sys::pal::common::small_c_string::run_path_with_cstr at small_c_string.rs:18:5
    frame #14: 0x000055a3eb60d54a pg`std::env::current_exe [inlined] std::sys::fs::read_link at mod.rs:80:5
    frame #15: 0x000055a3eb60d54a pg`std::env::current_exe [inlined] std::fs::read_link at fs.rs:2784:5
    frame #16: 0x000055a3eb60d54a pg`std::env::current_exe [inlined] std::sys::pal::unix::os::current_exe at os.rs:414:11
    frame #17: 0x000055a3eb60d4e9 pg`std::env::current_exe at env.rs:759:5
    frame #18: 0x000055a3eb5a5ab6 pg`findshlibs::linux::SharedLibrary::new(info=0x00007ffe906fb280, size=64, is_first_lib=true) at mod.rs:246:34
    frame #19: 0x000055a3eb3d3cf1 pg`findshlibs::linux::SharedLibrary::callback::{{closure}} at mod.rs:283:25
    frame #20: 0x000055a3eb39673d pg`core::ops::function::FnOnce::call_once((null)=<unavailable>, (null)=() @ 0x00007ffe906fb067) at function.rs:253:5
    frame #21: 0x000055a3eb3b6e49 pg`<core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once(self=<unavailable>, (null)=() @ 0x00007ffe906fb087) at unwind_safe.rs:272:9
    frame #22: 0x000055a3eb3ab13d pg`std::panicking::catch_unwind::do_call(data=0x00007ffe906fb138) at panicking.rs:589:40
    frame #23: 0x000055a3eb3b5b2b pg`__rust_try + 27
    frame #24: 0x000055a3eb3ab0a8 pg`std::panic::catch_unwind [inlined] std::panicking::catch_unwind(f=<unavailable>) at panicking.rs:552:19
    frame #25: 0x000055a3eb3ab04e pg`std::panic::catch_unwind(f=<unavailable>) at panic.rs:359:14
    frame #26: 0x000055a3eb3d3b6b pg`findshlibs::linux::SharedLibrary::callback(info=0x00007ffe906fb280, size=64, state=0x00007ffe906fb318) at mod.rs:281:15
    frame #27: 0x00007f107f9cb147 libc.so.6`dl_iterate_phdr + 407
    frame #28: 0x000055a3eb3d9c41 pg`<findshlibs::linux::SharedLibrary as findshlibs::SharedLibrary>::each(f=pprof::backtrace::framehop_unwinder::shlib::find_objects::{closure_env#0} @ 0x00007ffe906fb340) at mod.rs:351:13
    frame #29: 0x000055a3eb38c50f pg`pprof::backtrace::framehop_unwinder::shlib::find_objects at shlib.rs:59:5
    frame #30: 0x000055a3eb3969e2 pg`core::ops::function::FnOnce::call_once((null)=0x000055a3eb38c4e0, (null)=() @ 0x00007ffe906fb3cf) at function.rs:253:5
    frame #31: 0x000055a3eb3b53a0 pg`once_cell::sync::Lazy<T,F>::force::{{closure}} at lib.rs:1310:28
    frame #32: 0x000055a3eb3b575e pg`once_cell::sync::OnceCell<T>::get_or_init::{{closure}} at lib.rs:1120:57
    frame #33: 0x000055a3eb3aa313 pg`once_cell::imp::OnceCell<T>::initialize::{{closure}} at imp_std.rs:72:23
    frame #34: 0x000055a3eb5a5f56 pg`core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut(self=0x00007ffe906fb580, args=() @ 0x00007ffe906fb54f) at function.rs:301:21
    frame #35: 0x000055a3eb5a6fab pg`once_cell::imp::initialize_or_wait(queue=0x000055a3eb672b40, init=core::option::Option<&mut dyn core::ops::function::FnMut<(), Output=bool>>::Some @ 0x00007ffe906fb580) at imp_std.rs:196:20
    frame #36: 0x000055a3eb3a9fe2 pg`once_cell::imp::OnceCell<T>::initialize(self=0x000055a3eb672b40, f=once_cell::sync::{impl#6}::get_or_init::{closure_env#0}<alloc::vec::Vec<framehop::unwinder::Module<alloc::vec::Vec<u8, alloc::alloc::Global>>, alloc::alloc::Global>, once_cell::sync::{impl#11}::force::{closure_env#0}<alloc::vec::Vec<framehop::unwinder::Module<alloc::vec::Vec<u8, alloc::alloc::Global>>, alloc::alloc::Global>, fn() -> alloc::vec::Vec<framehop::unwinder::Module<alloc::vec::Vec<u8, alloc::alloc::Global>>, alloc::alloc::Global>>> @ 0x00007ffe906fb638) at imp_std.rs:68:9
    frame #37: 0x000055a3eb3b5851 pg`once_cell::sync::OnceCell<T>::get_or_try_init(self=0x000055a3eb672b40, f=once_cell::sync::{impl#6}::get_or_init::{closure_env#0}<alloc::vec::Vec<framehop::unwinder::Module<alloc::vec::Vec<u8, alloc::alloc::Global>>, alloc::alloc::Global>, once_cell::sync::{impl#11}::force::{closure_env#0}<alloc::vec::Vec<framehop::unwinder::Module<alloc::vec::Vec<u8, alloc::alloc::Global>>, alloc::alloc::Global>, fn() -> alloc::vec::Vec<framehop::unwinder::Module<alloc::vec::Vec<u8, alloc::alloc::Global>>, alloc::alloc::Global>>> @ 0x00007ffe906fb6b0) at lib.rs:1161:20
    frame #38: 0x000055a3eb3b56e4 pg`once_cell::sync::OnceCell<T>::get_or_init(self=0x000055a3eb672b40, f=once_cell::sync::{impl#11}::force::{closure_env#0}<alloc::vec::Vec<framehop::unwinder::Module<alloc::vec::Vec<u8, alloc::alloc::Global>>, alloc::alloc::Global>, fn() -> alloc::vec::Vec<framehop::unwinder::Module<alloc::vec::Vec<u8, alloc::alloc::Global>>, alloc::alloc::Global>> @ 0x00007ffe906fb6f0) at lib.rs:1120:24
    frame #39: 0x000055a3eb3b5331 pg`once_cell::sync::Lazy<T,F>::force(this=0x000055a3eb672b40) at lib.rs:1309:23
    frame #40: 0x000055a3eb3b1d5b pg`<once_cell::sync::Lazy<T,F> as core::ops::deref::Deref>::deref(self=0x000055a3eb672b40) at lib.rs:1376:13
    frame #41: 0x000055a3eb38c0b1 pg`pprof::backtrace::framehop_unwinder::shlib::get_objects at shlib.rs:12:5
    frame #42: 0x000055a3eb3939c4 pg`pprof::backtrace::framehop_unwinder::FramehopUnwinder::new at framehop_unwinder.rs:90:20
    frame #43: 0x000055a3eb393dd7 pg`pprof::backtrace::framehop_unwinder::UNWINDER::{{closure}}((null)=0x00007ffe906fb896) at framehop_unwinder.rs:126:60
    frame #44: 0x000055a3eb39668a pg`core::ops::function::FnOnce::call_once((null)=pprof::backtrace::framehop_unwinder::UNWINDER::{closure_env#0} @ 0x00007ffe906fb896, (null)=() @ 0x00007ffe906fb897) at function.rs:253:5
    frame #45: 0x000055a3eb3968a2 pg`core::ops::function::FnOnce::call_once((null)=0x000055a3eb396670, (null)=() @ 0x00007ffe906fb8bf) at function.rs:253:5
    frame #46: 0x000055a3eb3b550e pg`once_cell::sync::Lazy<T,F>::force_mut(this=0x000055a3eb672b68) at lib.rs:1330:32
    frame #47: 0x000055a3eb3b1d6b pg`<once_cell::sync::Lazy<T,F> as core::ops::deref::DerefMut>::deref_mut(self=0x000055a3eb672b68) at lib.rs:1382:13
    frame #48: 0x000055a3eb393e84 pg`<pprof::backtrace::framehop_unwinder::Trace as pprof::backtrace::Trace>::trace(ctx=0x00007ffe906fc440, cb=pprof::profiler::perf_signal_handler::{closure_env#0} @ 0x00007ffe906fba88) at framehop_unwinder.rs:165:18
    frame #49: 0x000055a3eb3d2606 pg`perf_signal_handler(_signal=27, _siginfo=0x00007ffe906fc570, ucontext=0x00007ffe906fc440) at profiler.rs:355:13
    frame #50: 0x00007f107f8a2070 libc.so.6`__restore_rt
    frame #51: 0x000055a3eb35ed90 pg`pg::is_prime_number3(v=15359, prime_numbers=size=1229) at main.rs:45:12
    frame #52: 0x000055a3eb35faaa pg`pg::main at main.rs:93:19
    frame #53: 0x000055a3eb358b5b pg`core::ops::function::FnOnce::call_once((null)=0x000055a3eb35f120, (null)=() @ 0x00007ffe906fd5cf) at function.rs:253:5
    frame #54: 0x000055a3eb33e4fe pg`std::sys::backtrace::__rust_begin_short_backtrace(f=0x000055a3eb35f120) at backtrace.rs:158:18
    frame #55: 0x000055a3eb359b91 pg`std::rt::lang_start::{{closure}} at rt.rs:206:18
    frame #56: 0x000055a3eb60c890 pg`std::rt::lang_start_internal [inlined] core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once at function.rs:290:21
    frame #57: 0x000055a3eb60c88d pg`std::rt::lang_start_internal [inlined] std::panicking::catch_unwind::do_call at panicking.rs:589:40
    frame #58: 0x000055a3eb60c88d pg`std::rt::lang_start_internal [inlined] std::panicking::catch_unwind at panicking.rs:552:19
    frame #59: 0x000055a3eb60c88d pg`std::rt::lang_start_internal [inlined] std::panic::catch_unwind at panic.rs:359:14
    frame #60: 0x000055a3eb60c88d pg`std::rt::lang_start_internal [inlined] std::rt::lang_start_internal::{{closure}} at rt.rs:175:24
    frame #61: 0x000055a3eb60c3cf pg`std::rt::lang_start_internal [inlined] std::panicking::catch_unwind::do_call at panicking.rs:589:40
    frame #62: 0x000055a3eb60c3cf pg`std::rt::lang_start_internal [inlined] std::panicking::catch_unwind at panicking.rs:552:19
    frame #63: 0x000055a3eb60c3cf pg`std::rt::lang_start_internal [inlined] std::panic::catch_unwind at panic.rs:359:14
    frame #64: 0x000055a3eb60c3cf pg`std::rt::lang_start_internal at rt.rs:171:5
    frame #65: 0x000055a3eb359b77 pg`std::rt::lang_start(main=0x000055a3eb35f120, argc=1, argv=0x00007ffe906fd8b8, sigpipe=0) at rt.rs:205:5
    frame #66: 0x000055a3eb35fb1e pg`main + 30
    frame #67: 0x00007f107f88b575 libc.so.6`__libc_start_call_main + 117
    frame #68: 0x00007f107f88b628 libc.so.6`__libc_start_main@@GLIBC_2.34 + 136
    frame #69: 0x000055a3eb3321a5 pg`_start + 37
```

### PR DESCRIPTION
**Pull request by YangKeao**
close #281

1. Initialize the `FramehopUnwinder` before the first call to the `perf_signal_handler`.
2. Add a test to make sure the signal handler doesn't have memory allocation.
3. Modify the github action to run related tests for framehop. I believe framehop will be a better choice (than `backtrace-rs`) in the future.
4. Modify the code to use `spin::RwLock` instead of the `static mut`, though there is no safety issue actually.

### CODE REVIEW

**Review by overvenus — APPROVED** [review]

File: src/profiler.rs [hunk 1]
```diff
@@ -524,3 +525,81 @@ impl Profiler {
...
+        PROFILER.write().as_mut().unwrap().start().unwrap();
+        let timer = Timer::new(999);
+        let start = std::time::Instant::now();
+        ALLOC.enable_count_alloc();
+
+        // busy loop for a while to trigger some samples
+        while start.elapsed().as_millis() < 500 {
+            std::hint::black_box(());
+        }
+        assert_eq!(ALLOC.alloc_count(), 0);
```
[the remark this answers is not in the document]
Comment (YangKeao) [reply src/profiler.rs]: Good idea! Done.

File: src/backtrace/framehop_unwinder.rs [hunk 2]
```diff
@@ -158,10 +160,22 @@ pub struct Trace;
...
+        let _ = UNWINDER.read();
+    }
+
     fn trace<F: FnMut(&Self::Frame) -> bool>(ctx: *mut c_void, cb: F)
     where
         Self: Sized,
     {
-        unsafe { UNWINDER.iter_frames(ctx, cb) };
+        // For Linux, this `try_write` should always succeed, because `SIGPROF` will never be delivered to
+        // another thread while the signal handler is running. However, I'm not sure about other OSes, so
```
Comment (korniltsev-grafanista) [inline src/backtrace/framehop_unwinder.rs:172]: > `SIGPROF` will never be delivered to another thread while the signal handler is running

Why? Do you have any pointers to source/documentation how we can double check that?

Comment (korniltsev-grafanista) [reply src/backtrace/framehop_unwinder.rs:172]: SIGPROF seem to be delivered concurrently to multiple threads , can you double check please  https://gist.github.com/korniltsev-grafanista/340064ee2a80b0fe9f95f64b29b13879

**Comment by korniltsev-grafanista** [comment]
can you tag a release with this commit please?
