### PR TITLE
Fix compilation error on arm architecture

### LINKED ISSUE #54: cross compiling failed
Hi there,
I tried to cross-compile rummqtt and got the following output.

```
roker/target/armv7-unknown-linux-gnueabihf/release/deps/libthiserror-eef2e33c746f6e56.rmeta --cap-lints allow`
error[E0308]: mismatched types
   --> /home/xx/.cargo/registry/src/github.com-1ecc6299db9ec823/pprof-0.4.1/src/profiler.rs:143:47
    |
143 |             write_thread_name(current_thread, &mut name);
    |                                               ^^^^^^^^^ expected slice `[u8]`, found array `[i8; 16]`
    |
    = note: expected mutable reference `&mut [u8]`
               found mutable reference `&mut [i8; 16]`

error[E0606]: casting `&mut [i8; 16]` as `*mut [u8]` is invalid
   --> /home/fwa/.cargo/registry/src/github.com-1ecc6299db9ec823/pprof-0.4.1/src/profiler.rs:141:28
    |
141 |             let name_ptr = &mut name as *mut [libc::c_char] as *mut libc::c_char;
    |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0308, E0606.
For more information about an error, try `rustc --explain E0308`.
error: could not compile `pprof`
```

Can you verify this?
Thanks in advance.

### PR DESCRIPTION
**Pull request by YangKeao**
Fix #54

### CODE REVIEW

File: examples/malloc_hook.rs [hunk 1]
```diff
@@ -5,7 +5,11 @@ extern crate libc;
 use pprof;
 use std::ffi::c_void;
 
+#[cfg(not(target_os = "linux"))]
+static mut __malloc_hook: Option<extern "C" fn(size: usize) -> *mut c_void> = None;
```
Comment (Hexilee) [inline examples/malloc_hook.rs:9]: Maybe we should skip the lint of this variable name.

**Review by Hexilee — APPROVED** [review]
Rest LGTM.
